name: Aluminum Price Daily Update

on:
  # 手动触发工作流
  workflow_dispatch:
  # 定时任务：北京时间每天10点5分运行
  schedule:
    - cron: '5 2 * * *'  # UTC时间2:00，对应北京时间10:00
    
  # 代码推送时触发
  push:
    branches:
      - main

jobs:
  crawl-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 步骤1：检出代码
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          
      # 步骤2：设置Python环境
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      # 步骤3：安装爬虫依赖
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml
          
      # 步骤4：执行爬虫获取最新铝价
      - name: Run Aluminum Price Crawler
        run: python crawler.py
        
      # 步骤5：提交更新的数据文件
      - name: Commit Updated Data
        id: commit
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add price-data.json
          git commit -m "Auto update: Aluminum price data $(date +'%Y-%m-%d %H:%M')" || exit 0
          
      # 步骤6：将更新推送到GitHub仓库
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          
      # 步骤7：设置GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v3
          
      # 步骤8：部署到GitHub Pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.'
          
      # 步骤9：部署到GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          target-branch: 'gh-pages'
