name: Deploy Aluminum Data
on:
  schedule:
    - cron: '5 2 * * *'  # 每天UTC 02:05（北京时间次日10:05）运行[9](@ref)
  push:
    branches: [main]

jobs:
  crawl-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Grant write permission
        run: chmod +x aluminum_price_crawler.py
  
      - name: Run crawler
        run: python aluminum_price_crawler.py  # 执行爬虫脚本
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAGES_DEPLOY }}
          publish_dir: ./  # 部署所有文件（含index.html和JSON）
          publish_branch: gh-pages

        - name: Debug - Check file existence
          run: |
                echo "当前工作目录: $(pwd)"
                ls -la  # 列出所有文件
                if [ -f aluminum_prices.json ]; then
                  echo "JSON文件存在，内容如下:"
                  cat aluminum_prices.json
                else
                  echo "错误：JSON文件未生成！"
                fi
