name: Aluminum Price Daily Update

on:
  workflow_dispatch: # 手动触发支持
  schedule:
    - cron: '5 2 * * *'  # UTC时间2:05 (北京时间10:05)
  push:
    branches: [ main ]

# 设置全局超时防止任务挂起
jobs:
  crawl-and-deploy:
    runs-on: ubuntu-latest
    # 全局超时设置，防止任务永久挂起
    timeout-minutes: 15
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 减少克隆深度，提升性能
          
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml
          
      - name: Run Crawler
        id: crawler
        run: python crawler.py
        
      - name: Check for Changes
        id: changes
        run: |
          git diff --quiet || echo "changes=true" >> $GITHUB_ENV
          git status
          
      # 仅在有变更时提交
      - name: Commit Changes
        if: env.changes == 'true'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add price-data.json
          git commit -m "Auto-update: Aluminum price $(date +'%Y-%m-%d')"
          
      # 简化部署流程 - 直接推送到pages分支
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: .
          force_orphan: true  # 清除历史提交避免存储库过大
          keep_files: true  # 保留价格文件
